#!/bin/sh
# Build tp copy to where scripts are run
# 
#if [ -z "$1" ]; then
#   echo "Must specify a script in ./Prog/Utils"
#   exit 1
#fi

case "$1" in
  "") echo "Must specify a script in ./Prog/Utils"
  ;;
  x|xj|g) 
  cp $1 /storage/emulated/0/.
  ;;
  evnote.sh)
  cp $1 /data/data/com.termux/files/home/. 
  ;;
  *) 
  echo "$1 not in build"
  ;;
esac
