#!/bin/sh
# Build - installs scripts where they run
# 

case "$1" in
  "") echo "Must specify a script in .../Prog/Utils"
  ;;
  x|xj) 
  cp $1 /storage/emulated/0/.
  ;;
  g) 
  cp $1 /storage/emulated/0/.
  cp $1 $HOME/.
  ;;
  evnote|evnote.sh)
  cp evnote.sh /data/data/com.termux/files/home/.shortcuts
  cp evnote_show.sh /data/data/com.termux/files/home/.shortcuts
  ;;
  *) 
  echo "$1 not in build"
  ;;
esac
